# Numpy - Numerical Python


# Install the numpy

 pip install numpy

import numpy as np


In [2]:
# Numpy is used for scientific calculations and basic math as well.
#fast,easy to store and uses less memory
# To perform any calculations using NumPy we need to convert any of the list, tuple or dictionary to array(np.array function). once after converting we are good to perform the any of the operations
# length of the array should be same(If it's mismatched then will get an error)
# calculate the dimension using ndim in numpy, we can provide list or tuple, (We have 3D, 4D arrays and all which are like list of list)

In [3]:
data_1 = [2,4,6,8,10]
data_2 = [1,3,5,7,9]

In [4]:
print(data_1)

[2, 4, 6, 8, 10]


In [5]:
# performing operation using the tuple

import numpy as np

data_10 = np.array((2,4,6,8,10))
data_20= np.array((1,3,5,7,9))

#array_10 = np.array(data_10)
#array_20 = np.array(data_20)

result= data_10 + data_20

result

array([ 3,  7, 11, 15, 19])

In [6]:
print(data_2)

[1, 3, 5, 7, 9]


In [7]:
#here if you can observe it got concatenated not addition operation performed. So to perform any mathematical operations we need to convert list or tuple to a NumPy array.
print(data_1+data_2)

[2, 4, 6, 8, 10, 1, 3, 5, 7, 9]


In [8]:
import numpy as np

array_1 = np.array(data_1)
array_2 = np.array(data_2)

In [9]:
#If you can see here after conversion mathematical operations are working.
print(array_1+ array_2)

[ 3  7 11 15 19]


In [10]:
print(array_2/array_1)

[0.5        0.75       0.83333333 0.875      0.9       ]


In [11]:
#Now let's see the dimesions of array. 
# here we have only Single line of numbers. Hence, it's a single dimesional array

array_1.ndim

1

In [12]:
data_3 = ([1,2,3,4],[5,6,7,8],[9,10,11,12])
array_3 = np.array(data_3)

In [13]:
array_3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
array_3.ndim

2

In [15]:
# here if you can observe it's a 5 Dimensional array 
data_4 = np.array([[[[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]]])
data_4

array([[[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]]]]])

In [16]:
data_4.ndim

5

In [17]:
data_5 = np.array((((([1,2],[3,4],[5,6])))))
data_5

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
data_5.ndim

2

In [19]:
# here we are checking the length of an array

len(array_3)

3

In [20]:
# We can see the result is one though we passed 3 lists because it's inside the single list
# where as in array_3 we see 3 lists passed because it's inside a single tuple and multiple lists inside that tuple
# tuple we use ()
# list we use []
len(data_4)

1

In [21]:
data_5.shape

(3, 2)

In [25]:
#reshape just shows the how shaping/ sizing can be done but it doesn't alter the main data element.
# One dinesional array can't be reshaped. only 2 or 3 dimesional can be changed.
data_5.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
#resize works to alter the data sizes and returns the resizes values
#Before data_5 was (3,2) shape but now using resize functions we have changed it to (2,3) shape.

data_5.resize(2,3)

In [31]:
data_5.shape

(2, 3)

In [32]:
data_5

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# One dinesional array can be reshaped.

data_6 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [52]:
# 2 d array that contains 3 arrays of each 2 elements

arr = data_6.reshape(2,3, 2)
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [58]:
data_7 = np.array([1,4,3])
data_8 = np.array(["Sneha"])

data_9 = np.concatenate((data_7,data_8))
data_9

array(['1', '4', '3', 'Sneha'], dtype='<U11')

In [60]:
np.sort((data_6))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
np.desc((data_6))

AttributeError: module 'numpy' has no attribute 'desc'